{{- if .Values.cleanupCustomResources.forceDeletion }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-cleanup"
  labels:
    app: "{{ .Release.Name }}-cleanup"
  annotations:
    "helm.sh/hook": "pre-delete"
    "helm.sh/hook-weight": "3"
spec:
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-cleanup"
    spec:
      serviceAccountName: {{ include "spring-cloud-gateway.serviceAccountName" . }}
      containers:
      - name: kubectl
        image: "{{ .Values.kubectlImage.repository }}:{{ .Values.kubectlImage.tag }}"
        imagePullPolicy: "{{ .Values.kubectlImage.pullPolicy }}"
        command:
        - /bin/sh
        - -c
        - >
          kubectl delete scgrc --all --all-namespaces --ignore-not-found;
          kubectl delete scgm --all --all-namespaces --ignore-not-found;
          kubectl delete scg --all --all-namespaces --ignore-not-found;
          sleep 10;
      restartPolicy: Never
{{- end }}
