apiVersion: v1
kind: Service
metadata:
  name: {{ index .Values "scg-operator" "deploymentName" }}
  labels:
  {{- include "spring-cloud-gateway.labels" . | nindent 4 }}
spec:
  type: {{ index .Values "scg-operator" "serviceType" }}
  selector:
    app: {{ index .Values "scg-operator" "deploymentName" }}
  ports:
    - port: 80
      targetPort: 8080
      name: http
