apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ index .Values "scg-operator" "deploymentName" }}
  labels:
  {{- include "spring-cloud-gateway.labels" . | nindent 4 }}
spec:
  replicas: {{ index .Values "scg-operator" "replicaCount" }}
  selector:
    matchLabels:
      app: {{ index .Values "scg-operator" "deploymentName" }}
  template:
    metadata:
      labels:
        app: {{ index .Values "scg-operator" "deploymentName" }}
    spec:
      # imagePullSecrets:
      #   - name: {{ index .Values "scg-operator" "registryCredentialsSecret" }}
      serviceAccountName: {{ include "spring-cloud-gateway.serviceAccountName" . }}
      containers:
      - name: {{ index .Values "scg-operator" "deploymentName" }}
        image: {{ index .Values "scg-operator" "image" }}
        imagePullPolicy: {{ index .Values "scg-operator" "imagePullPollicy" }}
        env:
        - name: OPERATOR_GATEWAY_IMAGE_NAME
          value: {{ .Values.gateway.image }}
        - name: OPERATOR_INSTALL_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: OPERATOR_IMAGE_PULL_SECRET_NAME
          value: {{ index .Values "scg-operator" "registryCredentialsSecret" }}
        resources:
      {{- toYaml .Values.resources | nindent 12 }}

