{{- if .Values.rbacs.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scg-operator-resources-role
  labels:
  {{- include "spring-cloud-gateway.labels" . | nindent 4 }}
rules:
- apiGroups:
  - tanzu.vmware.com
  resources:
  - springcloudgateways
  - springcloudgatewaymappings
  - springcloudgatewayrouteconfigs
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
    - "tanzu.vmware.com"
  resources:
    - springcloudgateways/status
    - springcloudgatewaymappingss/status
    - springcloudgatewayrouteconfigs/status
  verbs:
    - patch
- apiGroups:
    - "" # "" indicates the core API group
  resources:
    - pods/status
  verbs:
    - patch
- apiGroups:
  - "" # "" indicates the core API group
  resources:
  - pods
  verbs:
  - list
  - watch
- apiGroups:
  - "" # "" indicates the core API group
  resources:
  - services
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch

- apiGroups:
  - "" # "" indicates the core API group
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - create

- apiGroups:
    - "" # "" indicates the core API group
  resources:
    - configmaps
  verbs:
    - list
    - watch

- apiGroups:
    - "" # "" indicates the core API group
  resources:
    - persistentvolumeclaims
  verbs:
    - create
    - list

- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create

- apiGroups:
    - ""
  resources:
    - serviceaccounts
  verbs:
    - create
    - update
    - list

- apiGroups:
    - ""
  resources:
    - endpoints
  verbs:
    - get
    - list

- apiGroups:
    - "discovery.k8s.io"
  resources:
    - endpointslices
  verbs:
    - get
    - list

- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete

- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
- apiGroups:
  - "coordination.k8s.io"
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch

- apiGroups:
    - rbac.authorization.k8s.io
  resources:
    - roles
    - rolebindings
  verbs:
    - create
    - update
    - list

- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete

{{- end }}
